### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by GeT1t** [Cirn09/idavscode#3]
```C:\Program Files\IDA\plugins\idavsc.py: invalid syntax (server.py, line 38)
Traceback (most recent call last):
  File "C:\Program Files\IDA\python\3\ida_idaapi.py", line 616, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA/plugins/idavsc.py", line 4, in <module>
    from dbg_server import Config, Server, DebugServerCannotStopError
  File "C:/Program Files/IDA/plugins\dbg_server\__init__.py", line 3, in <module>
    from .server import Server, DebugServerCannotStopError
  File "C:/Program Files/IDA/plugins\dbg_server\server.py", line 38
    match msg['type']:
            ^
SyntaxError: invalid syntax
```

**Comment by Cirn09** [comment]
Python >= 3.10
